spring.application.name=crud
server.port=3313
spring.datasource.url=jdbc:mysql://localhost:3306/crudprueba?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update